### PR TITLE
Add Turing Network

### PR DESCRIPTION
**Pull request by irsal**
# Checklist

- [x] Use the owner account that submitted registrar_reserve to [sign](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.polkadot.io#/signing) the project information, and fill in the signature.
- [x] After each update of the project information, please sign the latest data and submit the signature.
- [x] Add a description for your pr, the description includes the original data of the signature, signature account, and signature.

------
```
ParaID: '2114',
Project Name: 'Turing Network',
Description (en): 'Turing Network is an automation blockchain for Defi and recurring payments in Kusama.',
Parachain Crowdloans Allocation (en): 'https://oak.tech/turing/token/',
Auction Reward & Reward Vesting Schedule (en): 'https://oak.tech/turing/reward/',
Financing Information (en): 'https://medium.com/oak-blockchain/oak-network-raises-a-5-5m-seed-round-from-foundation-capital-greylock-and-hypersphere-ventures-6c957f1c1ab',
Website Link: 'https://oak.tech/turing/home/',
Twitter Link: 'https://twitter.com/oak_network',
Telegram Link: 'https://t.me/OAK_Announcements',
Discord Link: 'https://discord.gg/7W9UDvsbwh',
Medium Link: 'https://medium.com/oak-blockchain',
Github Link: 'https://github.com/OAK-Foundation/'
```
---------------

 Owner account: `CmxJEdEniSV6hGWoKfHWLR6h4A1dh5gD1vgzmD12osJvGsk`
 
 Signature: `0xa807441ed1b5d7982d260533c13fdeb270b2e57bfb24f3214f594767ab198a51fca379065dda96117614415532f7d11da1be40209e7a3cb6fd9a9a520bc88d89`
 
---------------

Screen Shot 2022-03-23 at 12 19 52 PM

### CODE REVIEW

**Comment by carlhong** [comment]
please sign the data with [owner account](https://kusama.subscan.io/account/CmxJEdEniSV6hGWoKfHWLR6h4A1dh5gD1vgzmD12osJvGsk)

**Review by carlhong — CHANGES_REQUESTED** [review]
Please sign the data with [owner account](https://kusama.subscan.io/account/CmxJEdEniSV6hGWoKfHWLR6h4A1dh5gD1vgzmD12osJvGsk)

**Comment by irsal** [comment]
@carlhong ✅

**Comment by carlhong** [comment]
image
Verified!

**Review by carlhong — APPROVED** [review]

**Comment by irsal** [comment]
@carlhong - anything else left before merge? (I do not have write access, so I cannot do so)

**Pull request merged**
